import {
  BusinessDTO,
  DEFAULT_COORDS,
  ItemDTO,
} from "@/app/_interfaces/interfaces";
import { createSlice, PayloadAction } from "@reduxjs/toolkit";

type InitialState = {
  searchStr: string;
  businesses: BusinessDTO[];
  productResults: ItemDTO[];
};

const initialState: InitialState = {
  searchStr: "",
  businesses: [
    {
      id: "1",
      name: "witty shawarma",
      address: { coords: DEFAULT_COORDS, name: "Ago Okota" },
      businessTypes: ["shawarma"],
      owner: "user-100101",
      deliveryPrice: 200,
      profileImg: "witty-sha.jpg",
      isOpen: true,
      slug: "witty-shawarma",
      recommendations: [
        {
          businessType: "shawarma",
          items: [
            {
              id: "item01",
              itemType: "shawarma",
              businessData: {
                id: "1",
                name: "witty shawarma",
                slug: "witty-shawarma",
                deliveryPrice: 200,
              },
              image: "witty-sha.jpg",
              name: "chicken shawarma",
              price: 3000,
              slug: "chicken-shawarma",
              createdAt: 1740738322952,
            },
            {
              id: "item02",
              itemType: "shawarma",
              businessData: {
                id: "1",
                name: "witty shawarma",
                slug: "witty-shawarma",
                deliveryPrice: 200,
              },
              image: "witty-sha.jpg",
              name: "turkey shawarma",
              price: 5000,
              slug: "turkey-shawarma",
              createdAt: 1740738522952,
            },
            {
              id: "item03",
              itemType: "shawarma",
              businessData: {
                id: "1",
                name: "witty shawarma",
                slug: "witty-shawarma",
                deliveryPrice: 200,
              },
              image: "witty-sha.jpg",
              name: "Double Roasted shawarma",
              price: 9000,
              slug: "Double-Roasted-shawarma",
              createdAt: 1740738922152,
            },
            {
              id: "item04",
              itemType: "shawarma",
              businessData: {
                id: "1",
                name: "witty shawarma",
                slug: "witty-shawarma",
                deliveryPrice: 200,
              },
              image: "witty-sha.jpg",
              name: "Pork shawarma",
              price: 4000,
              slug: "pork-shawarma",
              createdAt: 1740738422952,
            },
          ],
        },
      ],
      createdAt: 1740738322952,
    },
    {
      id: "2",
      name: "Premium shawarma",
      address: { coords: DEFAULT_COORDS, name: "Century, Ago" },
      businessTypes: ["shawarma"],
      owner: "user-100101",
      deliveryPrice: 300,
      profileImg: "witty-sha.jpg",
      isOpen: false,
      slug: "premium-shawarma",
      recommendations: [
        {
          businessType: "shawarma",
          items: [
            {
              id: "item05",
              itemType: "shawarma",
              businessData: {
                id: "2",
                name: "Premium shawarma",
                slug: "premium-shawarma",
                deliveryPrice: 300,
              },
              image: "witty-sha.jpg",
              name: "chicken shawarma",
              price: 3000,
              slug: "chicken-shawarma",
              createdAt: 1740738312952,
            },
            {
              id: "item06",
              itemType: "shawarma",
              businessData: {
                id: "2",
                name: "Premium shawarma",
                slug: "premium-shawarma",
                deliveryPrice: 300,
              },
              image: "witty-sha.jpg",
              name: "turkey shawarma",
              price: 2000,
              slug: "turkey-shawarma",
              createdAt: 1740738222952,
            },
            {
              id: "item07",
              itemType: "shawarma",
              businessData: {
                id: "2",
                name: "Premium shawarma",
                slug: "premium-shawarma",
                deliveryPrice: 300,
              },
              image: "witty-sha.jpg",
              name: "Double Roasted shawarma",
              price: 8000,
              slug: "Double-Roasted-shawarma",
              createdAt: 1740738822952,
            },
            {
              id: "item08",
              itemType: "shawarma",
              businessData: {
                id: "2",
                name: "Premium shawarma",
                slug: "premium-shawarma",
                deliveryPrice: 300,
              },
              image: "witty-sha.jpg",
              name: "Pork shawarma",
              price: 4000,
              slug: "pork-shawarma",
              createdAt: 1740738422952,
            },
          ],
        },
      ],
      createdAt: 1740738322952,
    },
    {
      id: "3",
      name: "witty shawarma 2",
      address: { coords: DEFAULT_COORDS, name: "Ago Okota" },
      businessTypes: ["shawarma"],
      owner: "user-100101",
      deliveryPrice: 200,
      profileImg: "witty-sha.jpg",
      isOpen: true,
      slug: "witty-shawarma-2",
      recommendations: [
        {
          businessType: "shawarma",
          items: [
            {
              id: "item09",
              itemType: "shawarma",
              businessData: {
                id: "3",
                name: "witty shawarma 2",
                slug: "witty-shawarma-2",
                deliveryPrice: 200,
              },
              image: "witty-sha.jpg",
              name: "chicken shawarma",
              price: 4000,
              slug: "chicken-shawarma",
              createdAt: 1740738422952,
            },
            {
              id: "item10",
              itemType: "shawarma",
              businessData: {
                id: "3",
                name: "witty shawarma 2",
                slug: "witty-shawarma-2",
                deliveryPrice: 200,
              },
              image: "witty-sha.jpg",
              name: "turkey shawarma",
              price: 6000,
              slug: "turkey-shawarma",
              createdAt: 1740738622952,
            },
            {
              id: "item11",
              itemType: "shawarma",
              businessData: {
                id: "3",
                name: "witty shawarma 2",
                slug: "witty-shawarma-2",
                deliveryPrice: 200,
              },
              image: "witty-sha.jpg",
              name: "Double Roasted shawarma",
              price: 8000,
              slug: "Double-Roasted-shawarma",
              createdAt: 1740738822952,
            },
            {
              id: "item12",
              itemType: "shawarma",
              businessData: {
                id: "3",
                name: "witty shawarma 2",
                slug: "witty-shawarma-2",
                deliveryPrice: 200,
              },
              image: "witty-sha.jpg",
              name: "Pork shawarma",
              price: 7000,
              slug: "pork-shawarma",
              createdAt: 1740738722952,
            },
          ],
        },
      ],
      createdAt: 1740738322952,
    },
    {
      id: "4",
      name: "Premium shawarma 2",
      address: { coords: DEFAULT_COORDS, name: "Century, Ago" },
      businessTypes: ["shawarma"],
      owner: "user-100101",
      deliveryPrice: 150,
      profileImg: "witty-sha.jpg",
      isOpen: true,
      slug: "Premium-shawarma-2",
      recommendations: [
        {
          businessType: "shawarma",
          items: [
            {
              id: "item13",
              itemType: "shawarma",
              businessData: {
                id: "4",
                name: "Premium shawarma 2",
                slug: "premium-shawarma-2",
                deliveryPrice: 150,
              },
              image: "witty-sha.jpg",
              name: "chicken shawarma",
              price: 8000,
              slug: "chicken-shawarma",
              createdAt: 1740738822952,
            },
            {
              id: "item14",
              itemType: "shawarma",
              businessData: {
                id: "4",
                name: "Premium shawarma 2",
                slug: "premium-shawarma-2",
                deliveryPrice: 150,
              },
              image: "witty-sha.jpg",
              name: "turkey shawarma",
              price: 9000,
              slug: "turkey-shawarma",
              createdAt: 1740738922952,
            },
            {
              id: "item15",
              itemType: "shawarma",
              businessData: {
                id: "4",
                name: "Premium shawarma 2",
                slug: "premium-shawarma-2",
                deliveryPrice: 150,
              },
              image: "witty-sha.jpg",
              name: "Double Roasted shawarma",
              price: 1600,
              slug: "Double-Roasted-shawarma",
              createdAt: 1740738022952,
            },
            {
              id: "item16",
              itemType: "shawarma",
              businessData: {
                id: "4",
                name: "Premium shawarma 2",
                slug: "premium-shawarma-2",
                deliveryPrice: 150,
              },
              image: "witty-sha.jpg",
              name: "Pork shawarma",
              price: 7000,
              slug: "pork-shawarma",
              createdAt: 1740738722952,
            },
          ],
        },
      ],
      createdAt: 1740738322952,
    },
  ],
  productResults: [
    {
      id: "item01",
      itemType: "shawarma",
      businessData: {
        id: "1",
        name: "witty shawarma",
        slug: "witty-shawarma",
        deliveryPrice: 200,
      },
      image: "witty-sha.jpg",
      name: "chicken shawarma",
      price: 3000,
      slug: "chicken-shawarma",
      createdAt: 1740738322952,
    },
    {
      id: "item02",
      itemType: "shawarma",
      businessData: {
        id: "1",
        name: "witty shawarma",
        slug: "witty-shawarma",
        deliveryPrice: 200,
      },
      image: "witty-sha.jpg",
      name: "turkey shawarma",
      price: 5000,
      slug: "turkey-shawarma",
      createdAt: 1740738522952,
    },
    {
      id: "item03",
      itemType: "shawarma",
      businessData: {
        id: "1",
        name: "witty shawarma",
        slug: "witty-shawarma",
        deliveryPrice: 200,
      },
      image: "witty-sha.jpg",
      name: "Double Roasted shawarma",
      price: 9000,
      slug: "Double-Roasted-shawarma",
      createdAt: 1740738922152,
    },
    {
      id: "item04",
      itemType: "shawarma",
      businessData: {
        id: "1",
        name: "witty shawarma",
        slug: "witty-shawarma",
        deliveryPrice: 200,
      },
      image: "witty-sha.jpg",
      name: "Pork shawarma",
      price: 4000,
      slug: "pork-shawarma",
      createdAt: 1740738422952,
    },
    {
      id: "item05",
      itemType: "shawarma",
      businessData: {
        id: "2",
        name: "Premium shawarma",
        slug: "premium-shawarma",
        deliveryPrice: 300,
      },
      image: "witty-sha.jpg",
      name: "chicken shawarma",
      price: 3000,
      slug: "chicken-shawarma",
      createdAt: 1740738312952,
    },
    {
      id: "item06",
      itemType: "shawarma",
      businessData: {
        id: "2",
        name: "Premium shawarma",
        slug: "premium-shawarma",
        deliveryPrice: 300,
      },
      image: "witty-sha.jpg",
      name: "turkey shawarma",
      price: 2000,
      slug: "turkey-shawarma",
      createdAt: 1740738222952,
    },
    {
      id: "item07",
      itemType: "shawarma",
      businessData: {
        id: "2",
        name: "Premium shawarma",
        slug: "premium-shawarma",
        deliveryPrice: 300,
      },
      image: "witty-sha.jpg",
      name: "Double Roasted shawarma",
      price: 8000,
      slug: "Double-Roasted-shawarma",
      createdAt: 1740738822952,
    },
    {
      id: "item08",
      itemType: "shawarma",
      businessData: {
        id: "2",
        name: "Premium shawarma",
        slug: "premium-shawarma",
        deliveryPrice: 300,
      },
      image: "witty-sha.jpg",
      name: "Pork shawarma",
      price: 4000,
      slug: "pork-shawarma",
      createdAt: 1740738422952,
    },
    {
      id: "item09",
      itemType: "shawarma",
      businessData: {
        id: "3",
        name: "witty shawarma 2",
        slug: "witty-shawarma-2",
        deliveryPrice: 200,
      },
      image: "witty-sha.jpg",
      name: "chicken shawarma",
      price: 4000,
      slug: "chicken-shawarma",
      createdAt: 1740738422952,
    },
    {
      id: "item10",
      itemType: "shawarma",
      businessData: {
        id: "3",
        name: "witty shawarma 2",
        slug: "witty-shawarma-2",
        deliveryPrice: 200,
      },
      image: "witty-sha.jpg",
      name: "turkey shawarma",
      price: 6000,
      slug: "turkey-shawarma",
      createdAt: 1740738622952,
    },
    {
      id: "item11",
      itemType: "shawarma",
      businessData: {
        id: "3",
        name: "witty shawarma 2",
        slug: "witty-shawarma-2",
        deliveryPrice: 200,
      },
      image: "witty-sha.jpg",
      name: "Double Roasted shawarma",
      price: 8000,
      slug: "Double-Roasted-shawarma",
      createdAt: 1740738822952,
    },
    {
      id: "item12",
      itemType: "shawarma",
      businessData: {
        id: "3",
        name: "witty shawarma 2",
        slug: "witty-shawarma-2",
        deliveryPrice: 200,
      },
      image: "witty-sha.jpg",
      name: "Pork shawarma",
      price: 7000,
      slug: "pork-shawarma",
      createdAt: 1740738722952,
    },
    {
      id: "item13",
      itemType: "shawarma",
      businessData: {
        id: "4",
        name: "Premium shawarma 2",
        slug: "premium-shawarma-2",
        deliveryPrice: 150,
      },
      image: "witty-sha.jpg",
      name: "chicken shawarma",
      price: 8000,
      slug: "chicken-shawarma",
      createdAt: 1740738822952,
    },
    {
      id: "item14",
      itemType: "shawarma",
      businessData: {
        id: "4",
        name: "Premium shawarma 2",
        slug: "premium-shawarma-2",
        deliveryPrice: 150,
      },
      image: "witty-sha.jpg",
      name: "turkey shawarma",
      price: 9000,
      slug: "turkey-shawarma",
      createdAt: 1740738922952,
    },
    {
      id: "item15",
      itemType: "shawarma",
      businessData: {
        id: "4",
        name: "Premium shawarma 2",
        slug: "premium-shawarma-2",
        deliveryPrice: 150,
      },
      image: "witty-sha.jpg",
      name: "Double Roasted shawarma",
      price: 1600,
      slug: "Double-Roasted-shawarma",
      createdAt: 1740738022952,
    },
    {
      id: "item16",
      itemType: "shawarma",
      businessData: {
        id: "4",
        name: "Premium shawarma 2",
        slug: "premium-shawarma-2",
        deliveryPrice: 150,
      },
      image: "witty-sha.jpg",
      name: "Pork shawarma",
      price: 7000,
      slug: "pork-shawarma",
      createdAt: 1740738722952,
    },
  ],
};

const ActivitySlice = createSlice({
  name: "activity",
  initialState,
  reducers: {
    setSearchStr(state, action: PayloadAction<string>) {
      state.searchStr = action.payload;
    },
  },
});

export const { setSearchStr } = ActivitySlice.actions;

export const getActivity = (state: { activity: InitialState }) =>
  state.activity;

const ActivitySliceReducer = ActivitySlice.reducer;
export default ActivitySliceReducer;
